### ISSUE TITLE
Needs an RSS feed

### ISSUE THREAD

**Issue by causal-agent** [fasterthanlime/dev-rage.com#1]
Am I the only one who uses RSS or something?

**Comment by duckinator** [comment]
No, Scott uses it.
I think you two are alone though.

**Comment by causal-agent** [comment]
How else do you keep up to date with things like stupid webcomics and blogs?

**Comment by duckinator** [comment]
I don't :D

**Comment by nddrylliog** [comment]
Yeah, already been asked for.

Patches welcome.</grin>
